### ISSUE TITLE
WC plugin is highly unstructured

### ISSUE THREAD

**Issue by szepeviktor** [VivaPayments/API#1783]
Hello! After taking a look at https://github.com/VivaPayments/API/blob/master/Plugins/wordpress/vivawallet-for-woocommerce/wc-vivawallet.php I've concluded that is lacks inner structure.

May I help modernizing it?

**Comment by matthewrgourd** [comment]
Hi @szepeviktor we're ok, thanks! An updated plugin for WooCommerce is available at https://woocommerce.com/products/viva-wallet-for-woocommerce. This has been some time in development but introduces significant improvements including native integration of our payment gateway with WooCommerce.

**Comment by szepeviktor** [comment]
I see.
"Viva Wallet for WooCommerce" looks much nicer from the inside.

Is there a way to contribute?

**Comment by matthewrgourd** [comment]
Hi @szepeviktor thanks for your offer but we're developing the plugin 100% ourselves.

**Comment by szepeviktor** [comment]
Okay Matthew.
I list here a few thing for you:

1. Remove useless line `includes/class-wc-vivawallet-refund.php:109`
1. Remove .DS_Store from all dirs
1. Move class PGWC_Vivawallet to its own file
1. Fill in the pot file's header, see `wp i18n make-pot`
1. Move changes from changelog.txt to a proper readme.txt - WP understands readme.md too
1. Complete composer.json until `composer validate --strict` says "OK"
1. Move `woocommerce/woocommerce-sniffs` to require-dev
1. Use `szepeviktor/phpstan-wordpress` for making/keeping your code Robust

**Comment by szepeviktor** [comment]
phpstan.neon.dist

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    # Raise! level: max
    level: 4
    inferPrivatePropertyTypeFromConstructor: true
    scanFiles:
        - vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php
        - woocommerce-vivawallet-gateway.php
        - includes/class-wc-vivawallet.php
        - includes/class-wc-vivawallet-refund.php
        - includes/admin/class-wc-vivawallet-source.php
        - includes/class-wc-vivawallet-helper.php
        # This was lifted out of woocommerce-vivawallet-gateway.php
        - class-PGWC_Vivawallet.php
    paths:
        - woocommerce-vivawallet-gateway.php
        - includes/
        # This was lifted out of woocommerce-vivawallet-gateway.php
        - class-PGWC_Vivawallet.php
```
